### PR TITLE
SIE-29 [CloudFunctions] Research on testing

### PR DESCRIPTION
**Pull request by liuhantao9**

### CODE REVIEW

**Comment by liuhantao9** [comment]
I need to rename the directory since "-" is not correctly following python naming convention. 
https://stackoverflow.com/questions/761519/is-it-ok-to-use-dashes-in-python-files-when-trying-to-import-them
This explains why you can't use dashes in file or directory names

**Comment by quanganhhoang** [comment]
nit: not related but you should name your branch like this `username-sie-xx-description` and your PR like this `SIE-XX Description`

**Comment by quanganhhoang** [comment]
and also please fix linter before you make a PR or else they will give you a ton of errors :D

**Comment by quanganhhoang** [comment]
> I need to rename the directory since "-" is not correctly following python naming convention.
> https://stackoverflow.com/questions/761519/is-it-ok-to-use-dashes-in-python-files-when-trying-to-import-them
> This explains why you can't use dashes in file or directory names

nice catch! Thank you!

**Comment by quanganhhoang** [comment]
could you leave some comments on how you'd run this test / how would this get deployed? Your account should be able to deploy and run this test I think hmm

EDIT: I made us a testing service account 🚀

**Comment by liuhantao9** [comment]
Step to run the test:
cd into the directory
`cd image_processing`

Then use function framework to run the test script
`functions-framework --source=test.py --target=test_upload_processed_images`

Lastly use postman to send a request to http://0.0.0.0:8080 with two parameters, bucket_name = sie-processed-images and source_file_folder = "The folder containing files that you want to upload"
`http://0.0.0.0:8080?bucket_name=sie-processed-images&source_file_folder=/Users/hantaoliu/Desktop/test/`

**Review by quanganhhoang — APPROVED** [review]

**Pull request merged**
